
log:
    log_level: info
    log_format: '[%(asctime)s] - %(filename)s->%(funcName)s - line:%(lineno)d - [%(levelname)s] - %(message)s'
#    log_format: '[%(asctime)s] - %(filename)s - line:%(lineno)d - [%(levelname)s] - %(message)s'

